### ISSUE TITLE
Problem running on Fedora

### ISSUE THREAD

**Issue by ArsenArsen** [tweekmonster/deoplete-clang2#19]
The following arises:
```
[deoplete] Traceback (most recent call last):                                                                                                                                                                                     
[deoplete]   File "/home/arsen/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/deoplete.py", line 467, in on_event                                                                                                                  
[deoplete]     source.on_event(context)                    
[deoplete]   File "/home/arsen/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 151, in on_event                                                                                                   
[deoplete]     cmd, flags = self.build_flags(context)      
[deoplete]   File "/home/arsen/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 506, in build_flags                                                                                                
[deoplete]     db_flags = self.find_db_flags(context)      
[deoplete]   File "/home/arsen/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 350, in find_db_flags                                                                                              
[deoplete]     for entry in json.load(fp):                 
[deoplete]   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load                                          
[deoplete]     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)                              
[deoplete]   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads                                         
[deoplete]     return _default_decoder.decode(s)           
[deoplete]   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode                                         
[deoplete]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                      
[deoplete]   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode                                     
[deoplete]     raise JSONDecodeError("Expecting value", s, err.value) from None                                       
[deoplete] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                    
[deoplete] Exception during clang2.on_event for event 'Init': Expecting value: line 1 column 1 (char 0).  Use :messages for error details. 
```

This worked fine on Gentoo and Arch so I don't know.

Thanks in advance

**Comment by aswinmohanme** [comment]
I'm running fedora 26 and cannot reproduce the issue.

**Comment by ArsenArsen** [comment]
I can't do it anymore, so I assume it fixed itself.
