### ISSUE TITLE
Fresh install throws an error?

### ISSUE THREAD

**Issue by monokrome** [tweekmonster/deoplete-clang2#37]
Not sure if useful, but it seems like I get an error after a fresh install. The error occurs whenever a new buffer is open for editing. Based on the output, I'm guessing whenever a buffer is read.

Figured someone else may have a similar issue or have ideas for the solution:

```
[deoplete] Traceback (most recent call last):
  File "/home/polar/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 591, in _on_event
    source.on_event(context)
  File "/home/polar/.vim/plugged/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 147, in on_event
    self.clang_path = context['vars'].get(
KeyError: 'vars'
Exception during clang2.on_event for event 'Init': 'vars'.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/home/polar/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 591, in _on_event
    source.on_event(context)
  File "/home/polar/.vim/plugged/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 147, in on_event
    self.clang_path = context['vars'].get(
KeyError: 'vars'
Exception during clang2.on_event for event 'BufReadPost': 'vars'.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/home/polar/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 591, in _on_event
    source.on_event(context)
  File "/home/polar/.vim/plugged/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 147, in on_event
    self.clang_path = context['vars'].get(
KeyError: 'vars'
Exception during clang2.on_event for event 'BufReadPost': 'vars'.  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
I have fixed the error in deoplete.
Please update deoplete to the latest version.

**Comment by monokrome** [comment]
Well, that was fast :heart_eyes_cat: Thanks a bunch!!!
