### ISSUE TITLE
Throws errors when trying to type the name of an `#include`d header

### ISSUE THREAD

**Issue by HiPhish** [tweekmonster/deoplete-clang2#7]
Here are the steps:

- Create a new file (`touch derp.c`)
- Edit the file (`nvim derp.c`)
- Type the following: `#include <`
- Once I start typing the name of the header (e.g. `stdio.h`) deoplete throws the following errors:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/hiphish/.local/share/nvim/site-packages/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 116, in gather_results
[deoplete]     ctx['candidates'] = convert2candidates(ctx['candidates'])
[deoplete]   File "/Users/hiphish/.local/share/nvim/site-packages/deoplete.nvim/rplugin/python3/deoplete/util.py", line 51, in convert2candidates
[deoplete]     return [{'word': x} for x in l] if l and isinstance(l[0], str) else l
[deoplete] TypeError: 'generator' object is not subscriptable
[deoplete] Could not get completions from: clang2.  Use :messages for error details.
```

This happens every time. Any idea?

**Comment by tweekmonster** [comment]
> Any idea?

Yup.  Apparently deoplete doesn't like generators now.
